# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.4
    working_directory: ~/master
    steps:
      - checkout
      - run:
          name: Install Meteor
          command: "curl https://install.meteor.com | /bin/sh"
      - run:
          name: Install NPM dependencies
          command: meteor npm install
      - run:
          name: Install bcrypt
          command: "meteor npm install --save bcrypt"
      - run:
          name: Install PhantomJS
          command: "meteor npm i --save-dev phantomjs-prebuilt"
      - run:
          name: Run unit tests
          command: "TEST_BROWSER_DRIVER=phantomjs meteor test --once --driver-package meteortesting:mocha"
          shell: /bin/sh
workflows:
  version: 2
  Run tests for basic Meteor app:
    jobs:
      - build:
          filters:
            branches:
              only: master